name: CI (Markdown)

on:
  workflow_call:
    inputs:
      glob:
        description: Glob pattern for Markdown files
        type: string
        default: "**/*.md"

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: h13/.github/actions/apply-org-config@b45a509a3000ea5059c8c605c3d657ef473380e0 # main
        with:
          config-file: .markdownlint-cli2.yaml

      - uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7.1.0
        with:
          node-version: 24

      - run: npx markdownlint-cli2 "${{ inputs.glob }}"
