name: CI (Markdown)

on:
  workflow_call:
    inputs:
      glob:
        description: Glob pattern for Markdown files
        type: string
        default: "**/*.md"

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: h13/.github/actions/apply-org-config@027e68677754001ca07ed3f800899d3ec4e29f70 # main
        with:
          config-file: .markdownlint-cli2.yaml

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24

      - run: npx markdownlint-cli2 "${{ inputs.glob }}"
