name: CI (OpenTofu)

on:
  workflow_call:
    inputs:
      opentofu-version:
        description: OpenTofu version
        type: string
        default: "latest"

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: opentofu/setup-opentofu@a1320f892987e89d278cc92dc5adc984fb93aca4 # v2.0.2
        with:
          tofu_version: ${{ inputs.opentofu-version }}

      - run: tofu fmt -check -recursive
      - run: tofu init -backend=false
      - run: tofu validate

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: terraform-linters/setup-tflint@6e1e0642c0289bd619021bf6b34e3c08ed1e005a # v6.3.0

      - run: tflint --init
      - run: tflint --recursive
