name: CI (Terraform)

on:
  workflow_call:
    inputs:
      terraform-version:
        description: Terraform version
        type: string
        default: "latest"

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4
        with:
          terraform_version: ${{ inputs.terraform-version }}

      - run: terraform fmt -check -recursive
      - run: terraform init -backend=false
      - run: terraform validate

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: terraform-linters/setup-tflint@b480b8fcdaa6f2c577f8e4fa799e89e756bb7c93 # v6

      - run: tflint --init
      - run: tflint --recursive
