name: CI (Terraform)

on:
  workflow_call:
    inputs:
      terraform-version:
        description: Terraform version
        type: string
        default: "latest"

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
        with:
          terraform_version: ${{ inputs.terraform-version }}

      - run: terraform fmt -check -recursive
      - run: terraform init -backend=false
      - run: terraform validate

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: terraform-linters/setup-tflint@90f302c255ef959cbfb4bd10581afecdb7ece3e6 # v4

      - run: tflint --init
      - run: tflint --recursive
