name: CI

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/**"
      - "actions/**"
      - "sync/**"
      - ".markdownlint-cli2.yaml"
  pull_request:
    paths:
      - ".github/workflows/**"
      - "actions/**"
      - "sync/**"
      - ".markdownlint-cli2.yaml"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: rhysd/actionlint@393031adb9afb225ee52ae2ccd7a5af5525e03e8 # v1.7.11

  test-markdown:
    uses: ./.github/workflows/ci-markdown.yml
    with:
      glob: "{README,CONTRIBUTING,SECURITY,sync/**}.md"
