name: CI

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/**"
      - "actions/**"
      - ".markdownlint-cli2.yaml"
  pull_request:
    paths:
      - ".github/workflows/**"
      - "actions/**"
      - ".markdownlint-cli2.yaml"

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: rhysd/actionlint@a443f344ff32813837fa49f7aa6cbc478d770e62 # v1.7.9

  test-markdown:
    uses: ./.github/workflows/ci-markdown.yml
    with:
      glob: "README.md"
