name: Repo Sync

on:
  push:
    branches: [main]
    paths:
      - "sync/**"
      - ".github/sync.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: BetaHuhn/repo-file-sync-action@8d7590ac8bf240686428959b8fd060a34d508b3f # v1.9.4
        with:
          GH_PAT: ${{ secrets.REPO_SYNC_TOKEN }}
          CONFIG_PATH: .github/sync.yml
          PR_LABELS: repo-sync
          COMMIT_PREFIX: "chore: "
          COMMIT_BODY: "Synced from h13/.github"
          BRANCH_PREFIX: "chore/repo-sync-"
